### ISSUE TITLE
spam prevention

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/Loqi.me#25]
We've had some instances of IRC spam that should be easy to detect and automatically kick the person out.

* Any text posted with >50% all caps within 5 seconds of joining the channel (requires knowledge of when the person last joined the channel)
* Text that is all caps except for usernames (requires knowledge of current room list)

**Comment by aaronpk** [comment]
Mentioning the same link repeatedly. Needs some thought about a good limit, since people testing link preview is legit. Maybe the limit is >5 times within a minute and you're kicked. Maybe don't do rate limiting if you're  v since that means you're registered in the wiki.

**Comment by jjuran** [comment]
Loqi tracks everybody's karma, and could discriminate on that basis:  Be lenient for regulars (having at least 1 karma) but strict on newcomers.

**Comment by sknebel** [comment]
weird characters are another potential heuristic, since at least the recent spamwaves used those. Made slightly more complicated by the fact that 50% or so of the spammers mess up the encoding...

**Comment by sknebel** [comment]
and of course a "!spammer" command would also be an option. It could only work on recently joined users (that haven't been seen before) to prevent abuse.

**Comment by aaronpk** [comment]
I like the idea of giving the community the ability to help with this. That also happens to be the easiest thing to implement. Loqi now has a new `!kick` command.

* If you are +v (you're registered on irc-people), you can use the new `!kick` command
* You can say `!kick foobar` to kick that person from the room, but only if they joined less than 5 minutes ago

**Comment by aaronpk** [comment]
Just implemented two more anti-spam techniques.

* if you say more uppercase than lowercase characters other than the URL, and if you joined in the last 5 minutes, then you get kicked
* if you say the same URL 5 times within a minute, you get kicked

These only apply to people who are not +v registered on irc-people

**Comment by aaronpk** [comment]
This has gone through many iterations and has been pretty good at kicking spammers. Also thankfully the main spam wave has stopped.
