### ISSUE TITLE
ignore indieweb.social links

### ISSUE THREAD

**Issue by snarfed** [aaronpk/Loqi.me#45]
We're getting tweets for more and more indieweb.social links that aren't indieweb-related. Example: https://chat.indieweb.org/meta/2022-05-24#t1653408304376600 . Mind adding a regexp for eg `https://indieweb.social/.+` to a block/ignore-list? Thanks in advance!

(#30 is related.)

**Comment by aaronpk** [comment]
Should be blocked now, let me know if it pops up again.

**Comment by snarfed** [comment]
@aaronpk mind reopening?
